version: "3.6"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9900:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
      - "traefik.http.routers.portainer.entrypoints=web"

  traefik:
    image: traefik:v2.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9901:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  organizr:
    image: organizrtools/organizr-v2:armhf
    container_name: organizr
    restart: unless-stopped
    ports:
      - "9902:80"
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`organizr.${DOMAINNAME}`)"
      - "traefik.http.routers.organizr.entrypoints=web"

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9903:8123"
    privileged: true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAINNAME}`)"
      - "traefik.http.routers.homeassistant.entrypoints=web"

  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/mariadb:/config
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: jackgruber/phpmyadmin
    restart: unless-stopped
    links:
      - mariadb:db
    ports:
      - "9904:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"

  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: linuxserver/nextcloud
    links:
      - mariadb
    volumes:
      - ${USERDIR}/docker/nextcloud:/config
      - ${USERDIR}/docker/shared_data:/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9905:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAINNAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"

  ghost:
    image: ghost
    container_name: ghost
    restart: unless-stopped
    ports:
      - "9906:2368"
    environment:
      url: http://ghost.${DOMAINNAME}
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`ghost.${DOMAINNAME}`)"
      - "traefik.http.routers.ghost.entrypoints=web"

  gitlab:
    image: 'ulm0/gitlab'
    container_name: gitlab
    restart: unless-stopped
    hostname: '${DOMAINNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${DOMAINNAME}'
    ports:
      - '9907:80'
    volumes:
      - ${USERDIR}/docker/gitlab/config:/etc/gitlab
      - ${USERDIR}/docker/gitlab/logs:/var/log/gitlab
      - ${USERDIR}/docker/gitlab/data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAINNAME}`)"
      - "traefik.http.routers.gitlab.entrypoints=web"

  jenkins:
    image: jenkins4eval/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "9908:8080"
    volumes:
      - ${USERDIR}/docker/jenkins:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${DOMAINNAME}`)"
      - "traefik.http.routers.jenkins.entrypoints=web"

  monitor:
    image: michaelmiklis/rpi-monitor
    container_name: monitor
    restart: unless-stopped
    ports:
      - "9909:8888"
    devices:
      - /dev/vchiq
      - /dev/vcsm
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - ${USERDIR}/docker/monitor:/var/lib/rpimonitor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=Host(`monitor.${DOMAINNAME}`)"
      - "traefik.http.routers.monitor.entrypoints=web"

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    ports:
      - "9910:80"
    volumes:
      - ${USERDIR}/docker/heimdall:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${DOMAINNAME}`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
